# See https://pre-comit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
#  - repo: https://github.com/python-poetry/poetry
#    rev: 1.5.0
#    hooks:
#      - id: poetry-export
#        args: ["--without-hashes", "--output", "requirements.txt"]
#  - repo: https://github.com/python-poetry/poetry
#    rev: 1.5.0
#    hooks:
#      - id: poetry-export
#        args: ["--without-hashes", "--with", "dev", "--output", "requirements-dev.txt"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
#  - repo: https://github.com/dosisod/refurb
#    rev: v1.16.0
#    hooks:
#      - id: refurb
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
